# Generated by Django 2.2 on 2019-04-26 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raycom_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6, 'Value should be between 0 and 5'), django.core.validators.MaxValueValidator(-1, 'Value should be between 0 and 5')]),
        ),
    ]
