# Generated by Django 2.2 on 2019-04-26 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raycom_users', '0002_auto_20190426_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5, 'Value should be between 0 and 5'), django.core.validators.MinValueValidator(0, 'Value should be between 0 and 5')]),
        ),
    ]
